# Generated by Django 3.0.3 on 2020-03-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200302_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
