# Generated by Django 3.0.3 on 2020-02-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_auto_20200229_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(upload_to='read/documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='read/students/'),
        ),
    ]
