# Generated by Django 3.0.3 on 2020-02-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0004_auto_20200229_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='read/students/'),
        ),
    ]
