# Generated by Django 3.0.3 on 2020-03-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0005_auto_20200229_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='read/students/'),
        ),
    ]
