# Generated by Django 3.0.3 on 2020-03-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0009_auto_20200301_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='pending_requests',
        ),
    ]
