# Generated by Django 3.0.3 on 2020-03-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0010_remove_classroom_pending_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
