# Generated by Django 3.0.3 on 2020-03-05 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0011_document_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolled_in',
            old_name='enrolled_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateField(blank=True),
        ),
        migrations.CreateModel(
            name='Student_notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=300)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='read.Student')),
            ],
        ),
    ]
