# Generated by Django 3.0.3 on 2020-03-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0012_auto_20200305_0938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolled_in',
            unique_together={('student', 'classroom')},
        ),
    ]
