# Generated by Django 3.0.3 on 2020-03-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0013_auto_20200305_1045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('name', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='student_document',
            unique_together={('student', 'document')},
        ),
    ]
