# Generated by Django 3.0.3 on 2020-03-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0016_auto_20200307_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(null=True),
        ),
    ]
