# Generated by Django 3.0.3 on 2020-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0017_auto_20200316_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_document',
            name='pages_read',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='student_document',
            name='time_spent',
            field=models.TimeField(blank=True),
        ),
    ]
