# Generated by Django 3.0.3 on 2020-03-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0019_auto_20200327_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_document',
            name='pages_read',
        ),
        migrations.RemoveField(
            model_name='student_document',
            name='time_spent',
        ),
    ]
