# Generated by Django 3.0.3 on 2020-04-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0020_auto_20200327_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_document',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='read.Classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='student_document',
            unique_together={('student', 'classroom', 'document')},
        ),
    ]
