# Generated by Django 3.0.3 on 2020-04-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0021_auto_20200412_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_document',
            name='time_spent',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
