# Generated by Django 3.0.3 on 2020-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0022_student_document_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_document',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
